### ISSUE TITLE
Building flag partially depending on interactions flag

### ISSUE THREAD

**Issue by logannn61** [survanetwork/Worlds#88]
### ❗️ Please describe the issue

When the building flag is set to enabled and the player interactions flag is set to disabled people can break but not build

### ✅ How should it usually work?

The building flag should allow/prevent people to build/break blocks and the player interactions flag should allow/prevent to use items such as chests, furnaces, shulkers etc. So you can build with the player interactions flag set the disabled.

### 🗂 Steps to reproduce

Do /worlds set
Set the flag building to enabled
Set the flag player interactions to disabled
People will be able to break but not mine

### 🌱 Environment

Version of this plugin: 3.1.1
Version of PocketMine-MP:  4.3.2
Version of PHP: 8.0.15
OS: Linux

**Comment by jarne** [comment]
I think this issue is difficult to solve, as building blocks is technically seen as a form of interaction in PocketMine. There would be a lot of unclear edge cases. For example, should interacting with a lava bucket in the hand (which is in fact placing lava) be seen as interaction or building. Also, you could just break a chest you're not allowed to interact with to get its content.

For all use cases known to me, disabling interaction is usually done as a superset of disabling building. Is there any specific use case where it would be required to disable interactions but enable building?

I'm closing this issue for the moment, as I don't see a manageable way of solving it. But if we have a scenario where you would need this and an idea on how to differentiate between building and interaction, it might be re-opened.
